development:
  cloud_name: 'jh2tc'
  api_key: '888353585318946'
  api_secret: 'ECxqFQr3eILaxekBKHnWLPAteYQ'
  secure: true


development: 
  cloud_name: "dfuhjsd1x"
  api_key: "923345849312237"
  api_secret: "3rvaxEb9y6u5MLJQN-ISv0Si_Yc"
  secure: true

production:
  cloud_name: "dfuhjsd1x"
  api_key: "923345849312237"
  api_secret: "3rvaxEb9y6u5MLJQN-ISv0Si_Yc"
  secure:true